import sys
import os
import glob
import serial as sl
import time
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5 import QtWidgets, uic
import pyqtgraph as pg
from pyqtgraph import PlotWidget, plot
import numpy as np

status = "0"
finish = False
data = "empty"
ser = sl.Serial()
SerialPortName = ""
timer = 0
timeStep = 61





##############################################################################################
ser = sl.Serial("/dev/ttyACM0", 9600)
#ser = sl.Serial("COM5", 9600)
samplingPeriod = 0.1
O2Ymin = 0
O2Ymax = 1030
PYmin = 0
PYmax = 70
TempYmin = 0
TempYmax = 1030
TvYmin = 0
TvYmax = 1030
##############################################################################################

timeAxis = np.arange(-3.0, 0+samplingPeriod, samplingPeriod)

# ################################################
# global O2Ymin
# global O2Ymax
# global PYmin
# global PYmax
# global TempYmin
# global TempYmax
# global TvYmin
# global TvYmax
#
# self.O2Graph.plotItem.vb.setLimits(yMin=O2Ymin, yMax=O2Ymax)
# self.PressureGraph.plotItem.vb.setLimits(yMin=PYmin, yMax=PYmax)
# self.TempGraph.plotItem.vb.setLimits(yMin=TempYmin, yMax=TempYmax)
# self.TidalGraph.plotItem.vb.setLimits(yMin=TvYmin, yMax=TvYmax)
#
# global timeStep
# self.AlarmLabel.setStyleSheet("QLabel { background-color : green;}")
#
# # self.disableGroups()
#
# self.ListOfPorts = []
#
# self.O2_Gdata = [21 for i in range(len(timeAxis))]
# self.Pressure_Gdata = [15 for i in range(len(timeAxis))]
# self.temp_Gdata = [6 for i in range(len(timeAxis))]
# self.Tidal_Gdata = [25 for i in range(len(timeAxis))]
#
# self.seriaal = SerialReadThread()
# self.seriaal.data_received.connect(self.updateData)
# self.seriaal.Ser_Av.connect(self.enableGroups)
# self.seriaal.Ser_Wt.connect(self.disableGroups)
# self.seriaal.dev_Alrm.connect(self.alarmFunc)
# self.seriaal.plot_signal.connect(self.plot)
# self.seriaal.start()
#
# self.O2Input.valueChanged.connect(lambda: self.lcd_O2.display(str(self.O2Input.value())))
# self.TvInput.valueChanged.connect(lambda: self.lcd_Tv.display(str(self.TvInput.value())))
# self.BrInput.valueChanged.connect(lambda: self.lcd_Br.display(str(self.BrInput.value())))
# self.IrInput.valueChanged.connect(lambda: self.lcd_Ir.display(str(self.IrInput.value())))
# self.ApplyBtn_2.clicked.connect(self.clearBtn)
#
# self.StartBtn.clicked.connect(self.StartFunc)
# self.StopBtn.clicked.connect(self.StopFunc)
# self.ApplyBtn.clicked.connect(self.ApplyFunc)
#
# # for plus/minus buttons
# self.O2_plus.clicked.connect(self.O2_plusFUNC)
# self.O2_minus.clicked.connect(self.O2_minusFUNC)
#
# self.Tv_plus.clicked.connect(self.Tv_plusFUNC)
# self.Tv_minus.clicked.connect(self.Tv_minusFUNC)
#
# self.Br_plus.clicked.connect(self.Br_plusFUNC)
# self.Br_minus.clicked.connect(self.Br_minusFUNC)
#
# self.Ir_plus.clicked.connect(self.Ir_plusFUNC)
# self.Ir_minus.clicked.connect(self.Ir_minusFUNC)


def serial_ports():
    """ Lists serial port names

        :raises EnvironmentError:
            On unsupported or unknown platforms
        :returns:
            A list of the serial ports available on the system
    """
    if sys.platform.startswith('win'):
        ports = ['COM%s' % (i + 1) for i in range(256)]
    elif sys.platform.startswith('linux') or sys.platform.startswith('cygwin'):
        # this excludes your current terminal "/dev/tty"
        ports = glob.glob('/dev/tty[A-Za-z]*')
    elif sys.platform.startswith('darwin'):
        ports = glob.glob('/dev/tty.*')
    else:
        raise EnvironmentError('Unsupported platform for Serial')

    result = []
    for port in ports:
        try:
            s = sl.Serial(port)
            s.close()
            result.append(port)
        except (OSError, sl.SerialException):
            pass
    return result

class SerialReadThread(QtCore.QThread):
    data_received = QtCore.pyqtSignal(object)
    Ser_Av = QtCore.pyqtSignal(object)
    Ser_Wt = QtCore.pyqtSignal(object)
    dev_Alrm = QtCore.pyqtSignal(object)
    plot_signal = QtCore.pyqtSignal(object)
    def __init__(self):
        QtCore.QThread.__init__(self)
    def run(self):
        global data
        global finish
        global SerialPortName
        global ser
        global timer
        # while len(serial_ports()) == 0 or SerialPortName == "":
        #     self.Ser_Wt.emit(None)
        #     print(f'...waiting for Available Serial Ports')
        #     if len(serial_ports()) != 0:
        #         self.Ser_Av.emit(serial_ports())
        #         while SerialPortName == "":
        #             pass
        #     time.sleep(0.01)
        # ser = sl.Serial(SerialPortName, 9600)
        ser.flushInput()

        while not finish:
            try:
                if ser.inWaiting():  # Do while loop waiting for data
                    data = ser.readline().decode("ASCII")
                    word = data[:-1]
                    alrm = int(word.split(',')[4])
                    if alrm > 0:
                        self.dev_Alrm.emit(f'{alrm}')
                    self.data_received.emit(f'{data}')
                if timer == samplingPeriod*100:
                    self.plot_signal.emit(f'{data}')
                    timer = 0
                time.sleep(0.01)
                timer += 1
            except:
                #self.Ser_Wt.emit(None)
                self.dev_Alrm.emit(f'{4}')
                print(f'Error in Serial')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 790)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
       # pybutton = QtWidgets.QPushButton('Click me', self)
        #pybutton.resize(100,32)
       # pybutton.move(50, 50)      
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.ControlGroup = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(45)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlGroup.sizePolicy().hasHeightForWidth())
        self.ControlGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ControlGroup.setFont(font)
        self.ControlGroup.setStyleSheet("color: rgb(255, 255, 255);")
        self.ControlGroup.setObjectName("ControlGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ControlGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.ControlGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
    
        self.shutbutton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutbutton.sizePolicy().hasHeightForWidth())
        self.shutbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shutbutton.setFont(font)
        self.shutbutton.setStyleSheet("background-color: rgb(0, 149, 0);")
        self.shutbutton.setObjectName("shutbutton")
        self.horizontalLayout_10.addWidget(self.shutbutton)
        self.shutbutton.setIcon(QtGui.QIcon('/home/pi/download.png'))
        self.shutbutton.setIconSize(QtCore.QSize(50,50))

     
        self.StartBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartBtn.sizePolicy().hasHeightForWidth())
        self.StartBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn.setFont(font)
        self.StartBtn.setStyleSheet("background-color: rgb(0, 149, 0);")
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout_10.addWidget(self.StartBtn)
        #self.StartBtn = PicButton('/home/Pi/Desktop/download.png')
       
      
        
        self.StopBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopBtn.sizePolicy().hasHeightForWidth())
        self.StopBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StopBtn.setFont(font)
        self.StopBtn.setStyleSheet("background-color: rgb(218, 0, 0);")
        self.StopBtn.setObjectName("StopBtn")
        self.horizontalLayout_10.addWidget(self.StopBtn)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.ControlGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.lcd_O2 = QtWidgets.QLCDNumber(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_O2.sizePolicy().hasHeightForWidth())
        self.lcd_O2.setSizePolicy(sizePolicy)
        self.lcd_O2.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                  "color: rgb(255, 255, 255);")
        self.lcd_O2.setDigitCount(4)
        self.lcd_O2.setProperty("intValue", 20)
        self.lcd_O2.setObjectName("lcd_O2")
        self.horizontalLayout_2.addWidget(self.lcd_O2)
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.O2_minus = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O2_minus.sizePolicy().hasHeightForWidth())
        self.O2_minus.setSizePolicy(sizePolicy)
        self.O2_minus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.O2_minus.setObjectName("O2_minus")
        self.horizontalLayout_3.addWidget(self.O2_minus)
        self.O2Input = QtWidgets.QSlider(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O2Input.sizePolicy().hasHeightForWidth())
        self.O2Input.setSizePolicy(sizePolicy)
        self.O2Input.setMinimum(2)
        self.O2Input.setMaximum(10)
        self.O2Input.setSingleStep(1)
        self.O2Input.setPageStep(1)
        self.O2Input.setProperty("value", 2)
        self.O2Input.setOrientation(QtCore.Qt.Horizontal)
        self.O2Input.setObjectName("O2Input")
        self.horizontalLayout_3.addWidget(self.O2Input)
        self.O2_plus = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O2_plus.sizePolicy().hasHeightForWidth())
        self.O2_plus.setSizePolicy(sizePolicy)
        self.O2_plus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.O2_plus.setObjectName("O2_plus")
        self.horizontalLayout_3.addWidget(self.O2_plus)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.lcd_Tv = QtWidgets.QLCDNumber(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_Tv.sizePolicy().hasHeightForWidth())
        self.lcd_Tv.setSizePolicy(sizePolicy)
        self.lcd_Tv.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                  "color: rgb(255, 255, 255);")
        self.lcd_Tv.setDigitCount(4)
        self.lcd_Tv.setProperty("intValue", 5)
        self.lcd_Tv.setObjectName("lcd_Tv")
        self.horizontalLayout_4.addWidget(self.lcd_Tv)
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Tv_minus = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tv_minus.sizePolicy().hasHeightForWidth())
        self.Tv_minus.setSizePolicy(sizePolicy)
        self.Tv_minus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Tv_minus.setObjectName("Tv_minus")
        self.horizontalLayout_5.addWidget(self.Tv_minus)
        self.TvInput = QtWidgets.QSlider(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TvInput.sizePolicy().hasHeightForWidth())
        self.TvInput.setSizePolicy(sizePolicy)
        self.TvInput.setMinimum(0)
        self.TvInput.setMaximum(100)
        self.TvInput.setSingleStep(1)
        self.TvInput.setPageStep(1)
        self.TvInput.setProperty("value", 1)
        self.TvInput.setOrientation(QtCore.Qt.Horizontal)
        self.TvInput.setObjectName("TvInput")
        self.horizontalLayout_5.addWidget(self.TvInput)
        self.Tv_plus = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tv_plus.sizePolicy().hasHeightForWidth())
        self.Tv_plus.setSizePolicy(sizePolicy)
        self.Tv_plus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Tv_plus.setObjectName("Tv_plus")
        self.horizontalLayout_5.addWidget(self.Tv_plus)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.lcd_Br = QtWidgets.QLCDNumber(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_Br.sizePolicy().hasHeightForWidth())
        self.lcd_Br.setSizePolicy(sizePolicy)
        self.lcd_Br.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                  "color: rgb(255, 255, 255);")
        self.lcd_Br.setDigitCount(4)
        self.lcd_Br.setProperty("intValue", 8)
        self.lcd_Br.setObjectName("lcd_Br")
        self.horizontalLayout_6.addWidget(self.lcd_Br)
        self.label_20 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Br_minus = QtWidgets.QPushButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Br_minus.sizePolicy().hasHeightForWidth())
        self.Br_minus.setSizePolicy(sizePolicy)
        self.Br_minus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Br_minus.setObjectName("Br_minus")
        self.horizontalLayout_7.addWidget(self.Br_minus)
        self.BrInput = QtWidgets.QSlider(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BrInput.sizePolicy().hasHeightForWidth())
        self.BrInput.setSizePolicy(sizePolicy)
        self.BrInput.setMinimum(8)
        self.BrInput.setMaximum(40)
        self.BrInput.setSingleStep(1)
        self.BrInput.setPageStep(1)
        self.BrInput.setProperty("value", 8)
        self.BrInput.setOrientation(QtCore.Qt.Horizontal)
        self.BrInput.setObjectName("BrInput")
        self.horizontalLayout_7.addWidget(self.BrInput)
        self.Br_plus = QtWidgets.QPushButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Br_plus.sizePolicy().hasHeightForWidth())
        self.Br_plus.setSizePolicy(sizePolicy)
        self.Br_plus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Br_plus.setObjectName("Br_plus")
        self.horizontalLayout_7.addWidget(self.Br_plus)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_16 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_8.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.labelLCD = QtWidgets.QLCDNumber(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLCD.sizePolicy().hasHeightForWidth())
        self.labelLCD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLCD.setFont(font)
        self.labelLCD.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelLCD.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                    "color: rgb(255, 255, 255);")
        self.labelLCD.setSmallDecimalPoint(False)
        self.labelLCD.setDigitCount(1)
        self.labelLCD.setProperty("intValue", 1)
        self.labelLCD.setObjectName("labelLCD")
        self.horizontalLayout_8.addWidget(self.labelLCD)
        self.label = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.lcd_Ir = QtWidgets.QLCDNumber(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_Ir.sizePolicy().hasHeightForWidth())
        self.lcd_Ir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcd_Ir.setFont(font)
        self.lcd_Ir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcd_Ir.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                  "color: rgb(255, 255, 255);")
        self.lcd_Ir.setSmallDecimalPoint(False)
        self.lcd_Ir.setDigitCount(1)
        self.lcd_Ir.setProperty("intValue", 2)
        self.lcd_Ir.setObjectName("lcd_Ir")
        self.horizontalLayout_8.addWidget(self.lcd_Ir)
        self.label_2 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_9.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Ir_minus = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ir_minus.sizePolicy().hasHeightForWidth())
        self.Ir_minus.setSizePolicy(sizePolicy)
        self.Ir_minus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Ir_minus.setObjectName("Ir_minus")
        self.horizontalLayout_9.addWidget(self.Ir_minus)
        self.IrInput = QtWidgets.QSlider(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IrInput.sizePolicy().hasHeightForWidth())
        self.IrInput.setSizePolicy(sizePolicy)
        self.IrInput.setMinimum(1)
        self.IrInput.setMaximum(4)
        self.IrInput.setSingleStep(1)
        self.IrInput.setPageStep(1)
        self.IrInput.setProperty("value", 2)
        self.IrInput.setOrientation(QtCore.Qt.Horizontal)
        self.IrInput.setObjectName("IrInput")
        self.horizontalLayout_9.addWidget(self.IrInput)
        self.Ir_plus = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ir_plus.sizePolicy().hasHeightForWidth())
        self.Ir_plus.setSizePolicy(sizePolicy)
        self.Ir_plus.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.Ir_plus.setObjectName("Ir_plus")
        self.horizontalLayout_9.addWidget(self.Ir_plus)
        self.verticalLayout_7.addWidget(self.frame_18)
        self.verticalLayout_5.addWidget(self.frame_16)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.ControlGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ApplyBtn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ApplyBtn.sizePolicy().hasHeightForWidth())
        self.ApplyBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ApplyBtn.setFont(font)
        self.ApplyBtn.setStyleSheet("background-color: rgb(119, 39, 150);")
        self.ApplyBtn.setObjectName("ApplyBtn")
        self.horizontalLayout_11.addWidget(self.ApplyBtn)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.ControlGroup, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ReadGroup = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReadGroup.sizePolicy().hasHeightForWidth())
        self.ReadGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ReadGroup.setFont(font)
        self.ReadGroup.setStyleSheet("color: rgb(255, 255, 255);")
        self.ReadGroup.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.ReadGroup.setObjectName("ReadGroup")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.ReadGroup)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.ReadGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(75)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_22 = QtWidgets.QFrame(self.tab_6)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_46 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_15.addWidget(self.label_46)
        self.O2Output_lcd = QtWidgets.QLCDNumber(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O2Output_lcd.sizePolicy().hasHeightForWidth())
        self.O2Output_lcd.setSizePolicy(sizePolicy)
        self.O2Output_lcd.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                        "color: rgb(255, 255, 255);")
        self.O2Output_lcd.setDigitCount(8)
        self.O2Output_lcd.setProperty("intValue", 20)
        self.O2Output_lcd.setObjectName("O2Output_lcd")
        self.horizontalLayout_15.addWidget(self.O2Output_lcd)
        self.label_38 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("\n"
                                    "color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_15.addWidget(self.label_38)
        self.verticalLayout_8.addWidget(self.frame_22)
        self.frame_21 = QtWidgets.QFrame(self.tab_6)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_39 = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_14.addWidget(self.label_39)
        self.PressureOutput_lcd = QtWidgets.QLCDNumber(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PressureOutput_lcd.sizePolicy().hasHeightForWidth())
        self.PressureOutput_lcd.setSizePolicy(sizePolicy)
        self.PressureOutput_lcd.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                              "color: rgb(255, 255, 255);")
        self.PressureOutput_lcd.setDigitCount(8)
        self.PressureOutput_lcd.setProperty("intValue", 15)
        self.PressureOutput_lcd.setObjectName("PressureOutput_lcd")
        self.horizontalLayout_14.addWidget(self.PressureOutput_lcd)
        self.label_43 = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_14.addWidget(self.label_43)
        self.verticalLayout_8.addWidget(self.frame_21)
        self.frame_20 = QtWidgets.QFrame(self.tab_6)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_44 = QtWidgets.QLabel(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_13.addWidget(self.label_44)
        self.TempOutput_lcd = QtWidgets.QLCDNumber(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempOutput_lcd.sizePolicy().hasHeightForWidth())
        self.TempOutput_lcd.setSizePolicy(sizePolicy)
        self.TempOutput_lcd.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                          "color: rgb(255, 255, 255);")
        self.TempOutput_lcd.setDigitCount(8)
        self.TempOutput_lcd.setProperty("intValue", 6)
        self.TempOutput_lcd.setObjectName("TempOutput_lcd")
        self.horizontalLayout_13.addWidget(self.TempOutput_lcd)
        self.label_42 = QtWidgets.QLabel(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_13.addWidget(self.label_42)
        self.verticalLayout_8.addWidget(self.frame_20)
        self.frame_19 = QtWidgets.QFrame(self.tab_6)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_45 = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_12.addWidget(self.label_45)
        self.TvOutput_lcd = QtWidgets.QLCDNumber(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TvOutput_lcd.sizePolicy().hasHeightForWidth())
        self.TvOutput_lcd.setSizePolicy(sizePolicy)
        self.TvOutput_lcd.setStyleSheet("background-color: rgb(115, 115, 115);\n"
                                        "color: rgb(255, 255, 255);")
        self.TvOutput_lcd.setDigitCount(8)
        self.TvOutput_lcd.setProperty("intValue", 650)
        self.TvOutput_lcd.setObjectName("TvOutput_lcd")
        self.horizontalLayout_12.addWidget(self.TvOutput_lcd)
        self.label_36 = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_12.addWidget(self.label_36)
        self.verticalLayout_8.addWidget(self.frame_19)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.O2Graph = PlotWidget(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.O2Graph.sizePolicy().hasHeightForWidth())
        self.O2Graph.setSizePolicy(sizePolicy)
        self.O2Graph.setObjectName("O2Graph")
        self.verticalLayout_9.addWidget(self.O2Graph)
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.PressureGraph = PlotWidget(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.PressureGraph.sizePolicy().hasHeightForWidth())
        self.PressureGraph.setSizePolicy(sizePolicy)
        self.PressureGraph.setObjectName("PressureGraph")
        self.verticalLayout_10.addWidget(self.PressureGraph)
        self.label_47 = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_10.addWidget(self.label_47)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.TempGraph = PlotWidget(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.TempGraph.sizePolicy().hasHeightForWidth())
        self.TempGraph.setSizePolicy(sizePolicy)
        self.TempGraph.setObjectName("TempGraph")
        self.verticalLayout_11.addWidget(self.TempGraph)
        self.label_48 = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_11.addWidget(self.label_48)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TidalGraph = PlotWidget(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.TidalGraph.sizePolicy().hasHeightForWidth())
        self.TidalGraph.setSizePolicy(sizePolicy)
        self.TidalGraph.setObjectName("TidalGraph")
        self.verticalLayout_12.addWidget(self.TidalGraph)
        self.label_49 = QtWidgets.QLabel(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_12.addWidget(self.label_49)
        self.tabWidget.addTab(self.tab_10, "")
        self.verticalLayout_13.addWidget(self.tabWidget)
        self.frame_23 = QtWidgets.QFrame(self.ReadGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.AlarmLabel = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlarmLabel.sizePolicy().hasHeightForWidth())
        self.AlarmLabel.setSizePolicy(sizePolicy)
        self.AlarmLabel.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.AlarmLabel.setText("")
        self.AlarmLabel.setObjectName("AlarmLabel")
        self.horizontalLayout_16.addWidget(self.AlarmLabel)
        self.verticalLayout_13.addWidget(self.frame_23)
        self.DeviceMessageBox = QtWidgets.QTextBrowser(self.ReadGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.DeviceMessageBox.sizePolicy().hasHeightForWidth())
        self.DeviceMessageBox.setSizePolicy(sizePolicy)
        self.DeviceMessageBox.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.DeviceMessageBox.setObjectName("DeviceMessageBox")
        self.verticalLayout_13.addWidget(self.DeviceMessageBox)
        self.frame_24 = QtWidgets.QFrame(self.ReadGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.frame_24)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.ApplyBtn_2 = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ApplyBtn_2.sizePolicy().hasHeightForWidth())
        self.ApplyBtn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ApplyBtn_2.setFont(font)
        self.ApplyBtn_2.setStyleSheet("background-color: rgb(119, 39, 150);")
        self.ApplyBtn_2.setObjectName("ApplyBtn_2")
        self.horizontalLayout_17.addWidget(self.ApplyBtn_2)
        self.verticalLayout_13.addWidget(self.frame_24)
        self.gridLayout_2.addWidget(self.ReadGroup, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.menubar.setPalette(palette)
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "selection-background-color: rgb(97, 97, 97);")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ################################################
        global O2Ymin
        global O2Ymax
        global PYmin
        global PYmax
        global TempYmin
        global TempYmax
        global TvYmin
        global TvYmax

        self.O2Graph.plotItem.vb.setLimits(yMin=O2Ymin, yMax=O2Ymax)
        self.PressureGraph.plotItem.vb.setLimits(yMin=PYmin, yMax=PYmax)
        self.TempGraph.plotItem.vb.setLimits(yMin=TempYmin, yMax=TempYmax)
        self.TidalGraph.plotItem.vb.setLimits(yMin=TvYmin, yMax=TvYmax)

        global timeStep
        self.AlarmLabel.setStyleSheet("QLabel { background-color : green;}")

        # self.disableGroups()

        self.ListOfPorts = []

        self.O2_Gdata = [0 for i in range(len(timeAxis))]
        self.Pressure_Gdata = [0 for i in range(len(timeAxis))]
        self.temp_Gdata = [0 for i in range(len(timeAxis))]
        self.Tidal_Gdata = [0 for i in range(len(timeAxis))]

        self.seriaal = SerialReadThread()
        self.seriaal.data_received.connect(self.updateData)
        self.seriaal.Ser_Av.connect(self.enableGroups)
        self.seriaal.Ser_Wt.connect(self.disableGroups)
        self.seriaal.dev_Alrm.connect(self.alarmFunc)
        self.seriaal.plot_signal.connect(self.plot)
        self.seriaal.start()

        self.O2Input.valueChanged.connect(lambda: self.lcd_O2.display(str(self.O2Input.value())))
        self.TvInput.valueChanged.connect(lambda: self.lcd_Tv.display(str(self.TvInput.value())))
        self.BrInput.valueChanged.connect(lambda: self.lcd_Br.display(str(self.BrInput.value())))
        self.IrInput.valueChanged.connect(lambda: self.lcd_Ir.display(str(self.IrInput.value())))
        self.ApplyBtn_2.clicked.connect(self.clearBtn)




        self.StartBtn.clicked.connect(self.StartFunc)
        self.StopBtn.clicked.connect(self.StopFunc)
        self.ApplyBtn.clicked.connect(self.ApplyFunc)






        self.shutbutton.clicked.connect(self.restart)
        # for plus/minus buttons
        self.O2_plus.clicked.connect(self.O2_plusFUNC)
        self.O2_minus.clicked.connect(self.O2_minusFUNC)

        self.Tv_plus.clicked.connect(self.Tv_plusFUNC)
        self.Tv_minus.clicked.connect(self.Tv_minusFUNC)

        self.Br_plus.clicked.connect(self.Br_plusFUNC)
        self.Br_minus.clicked.connect(self.Br_minusFUNC)

        self.Ir_plus.clicked.connect(self.Ir_plusFUNC)
        self.Ir_minus.clicked.connect(self.Ir_minusFUNC)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ControlGroup.setTitle(_translate("MainWindow", "Device Controlling"))
        self.StartBtn.setText(_translate("MainWindow", "START"))
        self.StopBtn.setText(_translate("MainWindow", "STOP"))
        self.label_16.setText(_translate("MainWindow", "Oxygen       :"))
        self.label_15.setText(_translate("MainWindow", "(%)"))
        self.O2_minus.setText(_translate("MainWindow", "<"))
        self.O2_plus.setText(_translate("MainWindow", ">"))
        self.label_17.setText(_translate("MainWindow", "Tidal Volume:"))
        self.label_18.setText(_translate("MainWindow", "(% 750ml)"))
        self.Tv_minus.setText(_translate("MainWindow", "<"))
        self.Tv_plus.setText(_translate("MainWindow", ">"))
        self.label_19.setText(_translate("MainWindow", "Breath Rate :"))
        self.label_20.setText(_translate("MainWindow", "(BPM)"))
        self.Br_minus.setText(_translate("MainWindow", "<"))
        self.Br_plus.setText(_translate("MainWindow", ">"))
        self.label_21.setText(_translate("MainWindow", "Inhale to Breath:"))
        self.label.setText(_translate("MainWindow", ":"))
        self.Ir_minus.setText(_translate("MainWindow", "<"))
        self.Ir_plus.setText(_translate("MainWindow", ">"))
        self.ApplyBtn.setText(_translate("MainWindow", "APPLY CHANGES"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Controlling"))
        self.ReadGroup.setTitle(_translate("MainWindow", "Device Readings"))
        self.label_46.setText(_translate("MainWindow", "Oxygen :"))
        self.label_38.setText(_translate("MainWindow", "(%)"))
        self.label_39.setText(_translate("MainWindow", "Pressure:"))
        self.label_43.setText(_translate("MainWindow", "(cmH2O)"))
        self.label_44.setText(_translate("MainWindow", "Temp.   :"))
        self.label_42.setText(_translate("MainWindow", "(celsius)"))
        self.label_45.setText(_translate("MainWindow", "Tidal Vol.:"))
        self.label_36.setText(_translate("MainWindow", "(ml)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Numbers"))
        self.label_3.setText(_translate("MainWindow", "Oxygen Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Graph 1"))
        self.label_47.setText(_translate("MainWindow", "Pressure Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Graph 2"))
        self.label_48.setText(_translate("MainWindow", "Temperature  Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Graph 3"))
        self.label_49.setText(_translate("MainWindow", "Tidal Volume Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Graph 4"))
        self.label_4.setText(_translate("MainWindow", "Device Message:"))
        self.ApplyBtn_2.setText(_translate("MainWindow", "CLEAR"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Readings"))


    def O2_plusFUNC(self):
                current = self.O2Input.value()
                current += 1
                if current >= self.O2Input.maximum():
                    current = self.O2Input.maximum()
                self.O2Input.setValue(current)
                self.lcd_O2.display(str(self.O2Input.value() ))

    def O2_minusFUNC(self):
        current = self.O2Input.value()
        current -= 1
        if current <= self.O2Input.minimum():
            current = self.O2Input.minimum()
        self.O2Input.setValue(current)
        self.lcd_O2.display(str(self.O2Input.value() ))

    def Tv_plusFUNC(self):
        current = self.TvInput.value()
        current += 1
        if current >= self.TvInput.maximum():
            current = self.TvInput.maximum()
        self.TvInput.setValue(current)
        self.lcd_Tv.display(str(self.TvInput.value() ))

    def Tv_minusFUNC(self):
        current = self.TvInput.value()
        current -= 1
        if current <= self.TvInput.minimum():
            current = self.TvInput.minimum()
        self.TvInput.setValue(current)
        self.lcd_Tv.display(str(self.TvInput.value() ))

    def Br_plusFUNC(self):
        current = self.BrInput.value()
        current += 1
        if current >= self.BrInput.maximum():
            current = self.BrInput.maximum()
        self.BrInput.setValue(current)
        self.lcd_Br.display(str(self.BrInput.value()))

    def Br_minusFUNC(self):
        current = self.BrInput.value()
        current -= 1
        if current <= self.BrInput.minimum():
            current = self.BrInput.minimum()
        self.BrInput.setValue(current)
        self.lcd_Br.display(str(self.BrInput.value()))

    def Ir_plusFUNC(self):
        current = self.IrInput.value()
        current += 1
        if current >= self.IrInput.maximum():
            current = self.O2Input.maximum()
        self.IrInput.setValue(current)
        self.lcd_Ir.display(str(self.IrInput.value()))

    def Ir_minusFUNC(self):
        current = self.IrInput.value()
        current -= 1
        if current <= self.IrInput.minimum():
            current = self.IrInput.minimum()
        self.IrInput.setValue(current)
        self.lcd_Ir.display(str(self.IrInput.value()))


    def plot(self, data_list):
        
        global timeAxis
        word = data_list
        #print(word)
        temp = self.O2_Gdata[1:]
        self.O2_Gdata.clear()
        self.O2_Gdata.extend(temp)
        if(word.split(',')[0]!='empty'):
            self.O2_Gdata.append(int(word.split(',')[0]))
        else:
            self.O2_Gdata.append(0)
            
        temp = self.Pressure_Gdata[1:]
        self.Pressure_Gdata.clear()
        self.Pressure_Gdata.extend(temp)
        if(word.split(',')[0]!='empty'):
            self.Pressure_Gdata.append(int(word.split(',')[1]))
        else:
            self.Pressure_Gdata.append(0)
            


        temp = self.temp_Gdata[1:]
        self.temp_Gdata.clear()
        self.temp_Gdata.extend(temp)
        if(word.split(',')[0]!='empty'):
            self.temp_Gdata.append(int(word.split(',')[2]))
            
        else:
            self.temp_Gdata.append(0)        
        

        temp = self.Tidal_Gdata[1:]
        self.Tidal_Gdata.clear()
        self.Tidal_Gdata.extend(temp)
        if(word.split(',')[0]!='empty'):
            self.Tidal_Gdata.append(int(word.split(',')[3]))
        else:
            self.Tidal_Gdata.append(0) 


        self.O2Graph.clear()
        self.PressureGraph.clear()
        self.TempGraph.clear()
        self.TidalGraph.clear()

        self.O2Graph.plot(timeAxis, self.O2_Gdata, pen= pg.mkPen('g'))
        self.PressureGraph.plot(timeAxis, self.Pressure_Gdata, pen= pg.mkPen('g'))
        self.TempGraph.plot(timeAxis, self.temp_Gdata, pen= pg.mkPen('g'))
        self.TidalGraph.plot(timeAxis, self.Tidal_Gdata, pen= pg.mkPen('g'))

    def alarmFunc(self, number):
        number = int(number)
        if number == 4:
            self.DeviceMessageBox.setText(f'ALARM:\nNumber {number}\nERROR IN SERIAL, CHECK THE CONNECTION\nThen re-open the app.')
        else:
            self.DeviceMessageBox.setText(f'ALARM:\nNumber {number}')

        self.AlarmLabel.setStyleSheet("QLabel { background-color : red;}")

    def StartFunc(self):
        global status
        status = "1"
        self.sendData()

    def ApplyFunc(self):
        global status
        status = "1"
        self.sendData()

    def StopFunc(self):
        global status
        status = "0"
        self.sendData()
        #time.sleep(0.2)
        # exit(0)

    def clearBtn(self):
        self.DeviceMessageBox.clear()
        self.AlarmLabel.setStyleSheet("QLabel { background-color : green;}")

    def enableGroups(self, ports):
        for i in range(len(ports)):
            self.ListOfPorts.append(ports[i])
            self.menuSerial_Ports.addAction(f'{ports[i]}')
        for i in range(len(ports)):
            tempText = self.menuSerial_Ports.actions()[i].text()
            self.menuSerial_Ports.actions()[i].triggered.connect(lambda: self.SetSerName(tempText))

    def SetSerName(self, text):
        global SerialPortName
        SerialPortName = text
        self.ControlGroup.setEnabled(True)
        self.ReadGroup.setEnabled(True)

    def disableGroups(self):
        self.ControlGroup.setEnabled(False)
        self.ReadGroup.setEnabled(False)

    def updateData(self):
        global data
        word = data
        ListData = word.split(',')
        self.O2Output_lcd.display(str(ListData[0]))
        self.PressureOutput_lcd.display(str(ListData[1]))
        self.TempOutput_lcd.display(str(ListData[2]))
        self.TvOutput_lcd.display(str(ListData[3]))

    def sendData(self):
        global status
        Odata = str(self.O2Input.value())
        Tvata = str(self.TvInput.value())
        Bdata = str(self.BrInput.value())
        Idata = str(self.IrInput.value())
        totalData = '111'+','+status +','+ Odata +','+ Tvata +','+ Bdata +','+ Idata +','
        #print(f'to:{totalData}')
        print(totalData)
        ser.write(totalData.encode())

    def restart(self):
        command = "/usr/bin/sudo /sbin/shutdown -r now"
        import subprocess
        #process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
        #output = process.communicate()[0]
        import os
        os.system('sudo poweroff')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    flags = QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint)
    MainWindow.setWindowFlags(flags)
    #MainWindow.show()
    MainWindow.showMaximized()
    sys.exit(app.exec_())

